<project name="strutstestcase" default="all" basedir=".">

    <!-- ================ Initialize Property Values ================ -->

    <!-- set the release version -->
    <property name="major.version" value="0"/>
    <property name="minor.version" value="0"/>
    <property name="point.version" value="2"/>
    <property name="release.version" value="${major.version}${minor.version}${point.version}"/>
    <property name="jar.name" value="strutstest-uyuni-${major.version}.${minor.version}.${point.version}.jar"/>

    <!-- points to the top of a test application server -->
    <!-- used for automatic deployment of the test code -->
    <property name="appserver.home" value="${user.home}/appserver"/>

    <!-- compile options defaults -->
    <property name="comp.deprecate" value="off"/>
    <property name="comp.debug" value="on"/>
    <property name="comp.optimize" value="off"/>
    <property name="comp.verbose" value="off"/>
    <property name="comp.release" value="11"/>

    <!-- important directories -->
    <property name="build.dir" value="${basedir}/build"/>
    <property name="src.dir" value="${basedir}/src"/>
    <property name="distribute.dir" value="${basedir}/dist/strutstest"/>
    <property name="doc.dir" value="${distribute.dir}/docs"/>
    <property name="test.dir" value="${basedir}/test-results"/>
    <property name="temp.dir" value="${basedir}/temp"/>
    <property name="lib.dir" value="${basedir}/lib"/>

    <!-- ====================== Build Targets ====================== -->

    <!-- intialize build -->
    <target name="init">
        <echo message="Using Jakarta Servlet API (jakarta.servlet) and Struts Framework (struts)"/>
        <property name="servlet.version" value="5.0.0"/>
        <property name="struts.version" value="1.2.9"/>
        <path id="class.path">
            <fileset dir="${lib.dir}">
                <include name="*.jar"/>
                <include name="*.zip"/>
            </fileset>
            <pathelement location="${build.dir}"/>
        </path>
    </target>

    <target name="build" depends="init" description="compile all Java classes">
        <mkdir dir="${build.dir}"/>

        <javac srcdir="${src.dir}"
            destdir="${build.dir}"
            deprecation="${comp.deprecate}"
            debug="${comp.debug}"
            optimize="${comp.optimize}"
            verbose="${comp.verbose}"
            release="${comp.release}"
            includeantruntime="false"
            fork="true">
            <classpath refid="class.path"/>
            <include name="**/*.java"/>
        </javac>
    </target>

    <!-- package the application for deployment.  -->
    <target name="package" depends="build" description="package all Java classes">
        <mkdir dir="${distribute.dir}"/>
        <jar jarfile="${distribute.dir}/${jar.name}">
            <fileset dir="${build.dir}" includes="**/*.class" excludes="**/examples/**,**/tests/**"/>
        </jar>
    </target>

    <!-- prepare code for public release -->
    <target name="release" depends="init,package,docs">
        <echo message="creating release for servlet v${servlet.version} and struts v${struts.version}..."/>
        <zip zipFile="${basedir}/strutstest-uyuni${release.version}-${struts.version}_${servlet.version}.zip" basedir="${basedir}/dist"/>
    </target>

    <target name="release.src" depends="clean">
        <zip zipFile="${basedir}/strutstest-uyuni-${release.version}-src.zip" basedir="${basedir}">
            <exclude name="*.zip"/>
            <exclude name="lib/*.jar"/>
        </zip>
    </target>

    <!-- Clean up the build -->
    <target name="clean" description="remove all build products">
        <delete dir="${build.dir}"/>
        <delete dir="${basedir}/dist"/>
        <delete dir="${test.dir}"/>
        <delete file="${basedir}/test.war"/>
        <delete>
            <fileset dir="${basedir}" includes="strutstest*.zip"/>
        </delete>
    </target>

    <!-- Generate Javadocs for the application -->
    <target name="docs" description="compile documentation for all Java classes">
        <mkdir dir="${doc.dir}/api"/>
        <copy file="${basedir}/howto.htm" toDir="${doc.dir}"/>
        <copy file="${basedir}/faq.htm" toDir="${doc.dir}"/>
        <copy file="${basedir}/stylesheet.css" toDir="${doc.dir}"/>
        <copy file="${basedir}/LICENSE.TXT" toDir="${distribute.dir}"/>
        <copy file="${basedir}/README.TXT" toDir="${distribute.dir}"/>
        <mkdir dir="${distribute.dir}/examples"/>
        <copy todir="${distribute.dir}/examples">
            <fileset dir="${src.dir}/examples" excludes="**/tiles*.xml"/>
        </copy>
        <javadoc packagenames="servletunit,servletunit.struts"
            sourcepath="${src.dir}"
            destdir="${doc.dir}/api"
            author="true"
            version="true"
            use="true"
            windowtitle="StrutsTestCase Documentation"
            doctitle="&lt;H1&gt;StrutsTestCase for JUnit&lt;/H1&gt;"
            bottom="&lt;i&gt;Copyright &#169; Deryl Seale All Rights Reserved.&lt;/i&gt;">
            <group title="StrutsTestCase for JUnit" packages="servletunit.struts"/>
            <group title="ServletUnit Mock Object Framework" packages="servletunit"/>
            <!-- Put in links to JDK classes -->
            <link offline="false"
                href="https://docs.oracle.com/en/java/javase/21/docs/api/"/>
            <link offline="false"
                href="https://jakarta.ee/specifications/servlet/5.0/apidocs/"/>
        </javadoc>
        <copy todir="${distribute.dir}/examples" file="test.war"/>
    </target>

    <!-- Run unit tests -->
    <target name="test" depends="build" description="run all mock object tests">
        <mkdir dir="${test.dir}"/>

        <!-- Use the JUnit 5.10 Platform Console Standalone -->
        <!-- https://docs.junit.org/5.10.0/user-guide/index.html#running-tests-console-launcher -->
        <java fork="true" failonerror="false"
              classname="org.junit.platform.console.ConsoleLauncher">
            <classpath refid="class.path"/>
            <classpath>
                <pathelement location="${src.dir}/examples/"/>
                <pathelement location="${src.dir}/"/>
                <pathelement location="${lib.dir}/junit-platform-console-standalone-1.10.1.jar"/>
            </classpath>

            <sysproperty key="test.dir" value="${test.dir}"/>
            <sysproperty key="basedir" value="${basedir}"/>

            <!-- Scan classpath for tests -->
            <arg value="--scan-classpath"/>
            <arg value="--classpath"/>
            <arg value="${build.dir}"/>

            <!-- Include test packages -->
            <arg value="--include-package"/>
            <arg value="servletunit.struts"/>
            <arg value="--include-package"/>
            <arg value="servletunit.tests"/>

            <!-- Output reports -->
            <arg value="--reports-dir"/>
            <arg value="${test.dir}"/>
        </java>

    </target>

    <target name="deploy" depends="package">
        <copy todir="${appserver.home}/webapps" file="${distribute.dir}/${jar.name}" overwrite="true"/>
    </target>

    <!-- Run all the build targets -->
    <target name="all" description="build the StrutsTestCase library" depends="clean,build,package,deploy"/>

    <target name="auto.build" depends="clean,build,test,package,deploy"/>

</project>
